name: Check

on:
  push:
    branches: [main]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency:
      group: lint-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - name: Format
        run: cargo fmt --check --all
      - name: Lint
        run: cargo clippy --all-targets --all-features
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    concurrency:
      group: build-and-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - name: Build
        run: cargo build --verbose --all-features
      - name: Run tests
        run: cargo test --verbose --all-features
